### ISSUE TITLE
People who have unsubscribed and resubscribed to the mailing list appear to not be succcessfully added

### ISSUE THREAD

**Issue by christopherhafke** [michiganhackers/mh-web-backend#5]
See this endpoint: https://dev.mailjet.com/email/reference/contacts/contact/

**Comment by christopherhafke** [comment]
The problem may be that the email is already in the global contact list. We may have to first issue a `GET` request to see if the email is already there, then issue either a `POST` request or a `PUT` request as necessary.

**Comment by eashwar** [comment]
won't fix
